### PR TITLE
Remove datastore

### LINKED ISSUE #32: Datastore config is too complicated
Using a colon-delimited string for datastore configuration is complicated and annoying.
It should be converted to a key-value series. Examples:

``` hcl
server {
  datastore {
    type = "mysql"
    username = "user"
    password = "passwd"
    address = "my-db-host.corp:3306"
  }
}

server {
  datastore {
    type = "mongo"
    username = "user"
    password = "passwd"
    address = "my-mongo-host1.corp,my-mongo-host2.corp"
  }
}

server {
  datastore {
    type = "sqlite"
    filename = "/data/cashier.db"
  }
}
```

This has the benefit of making it easier to use vault for datastore passwords.
This will break existing configs so some form of detection and warning or compatibility should be employed.

### PR DESCRIPTION
**Pull request by lyda**
This is built on top of the `no-mongo` PR (they overlap in the docs).

This should resolve #32.

### CODE REVIEW

**Comment by nsheridan** [comment]
Why did you close this? It wasn't merged

**Comment by lyda** [comment]
Gah!

**Comment by lyda** [comment]
And today's the day Kevin learns to use the reflog...

**Comment by lyda** [comment]
Ha - the hash I needed was on this page.

I was cleaning old branches out of my trees. I mistakenly pruned too much. Recreated it and pushed again.

Also, does this comment make me sound like a stoner lumberjack?

**Pull request merged**
