### PR TITLE
client: use a config file in addition to command-line flags

### LINKED ISSUE #5: cashier cmd should read CA from dotfile
having a default value doesn't make sense for other users, also passing it all the time is a PITA. let's have a really simple dotfile for storing these defaults. also makes provisioning in orgs much easier.

### PR DESCRIPTION
**Pull request by nsheridan**
fixes #5

### CODE REVIEW

**Comment by patrickod** [comment]
wondering if this should be an either/or addition with config files? running for the first time without `$HOME/.cashier.cfg` in place isn't the best experience as it just dies saying it can't read the config file which you don't necessarily know about ahead of time. 

One thought is that were this packaged you could have a nice manpage or `share` folder example to copy, but in the meantime I think it'd be nice to maintain the config-less run options. thoughts?

**Comment by nsheridan** [comment]
Yeah, pulling a fatal on lack of config file is a bad idea and is actually really easy to solve - I've already set defaults for the config options so I should change the error to just printing these and continuing with a warning about lack of config file.

**Comment by patrickod** [comment]
Additional thought: thinking of adding a `validate_tls_certificate` boolean (default true of course) to the client config to make local testing easier. Not a **huge** fan of foot-gun options like this but without it TLS development is somewhat of a PITA

**Comment by patrickod** [comment]
Added said configuration option. Don't think we should put it in the `example-client.cfg` file but instead in the README to notify people of the option. Thinking of it strictly as a development aid.

**Comment by nsheridan** [comment]
I've re-added flags using the pflags package which natively allows binding to the viper config.
Order precedence appears to be: flags set defaults, config overrides defaults, flags explicitly set on commandline overrides everything.

I haven't documented the `validate_tls_certificate` option anywhere yet. I'm ok with leaving it undocumented for now.

**Pull request merged**
